version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10

    steps:
      - checkout
      - restore_cache:
          name: Restore yarn and Cypress cache
          keys:
            - dependency-cache
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - run:
          name: Run web server
          command: ENV=cypress yarn start
          background: true
      - run:
          name: Run tests
          command: yarn cypress:circleCi
      - run:
          name: Run linter
          command: yarn lint

      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache
